# Generated by Django 2.2.1 on 2019-05-05 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('order', models.IntegerField()),
                ('value', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='sublesson',
            name='expression',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sublesson',
            name='variables',
            field=models.ManyToManyField(to='website.Variable'),
        ),
    ]
