# Generated by Django 2.2.1 on 2019-05-05 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20190505_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sublesson',
            name='variables',
        ),
        migrations.AddField(
            model_name='variable',
            name='sublesson',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='website.SubLesson'),
            preserve_default=False,
        ),
    ]
