# Generated by Django 2.2.1 on 2019-05-05 02:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0003_auto_20190505_0139'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubLessonUserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.IntegerField()),
                ('time', models.DurationField()),
                ('learn_type', models.CharField(max_length=128)),
                ('sublesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.SubLesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
