# Generated by Django 2.2.1 on 2019-05-05 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_sublessonuserdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='sublessonuserdata',
            name='tries',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
