# Generated by Django 2.2.1 on 2019-05-05 04:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_sublessonuserdata_tries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sublessonuserdata',
            name='problem',
        ),
        migrations.AddField(
            model_name='sublessonuserdata',
            name='current_answer',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='sublessonuserdata',
            name='current_problem',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='sublessonuserdata',
            name='learn_type',
            field=models.CharField(default='Logical', max_length=128),
        ),
        migrations.AlterField(
            model_name='sublessonuserdata',
            name='time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='sublessonuserdata',
            name='tries',
            field=models.IntegerField(default=1),
        ),
    ]
