# Generated by Django 2.2.1 on 2019-05-05 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20190505_0439'),
    ]

    operations = [
        migrations.AddField(
            model_name='sublessonuserdata',
            name='solved',
            field=models.BooleanField(default=False),
        ),
    ]
