# Generated by Django 2.2.1 on 2019-05-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_sublessonuserdata_solved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sublessonuserdata',
            name='learn_type',
        ),
        migrations.AddField(
            model_name='sublessonuserdata',
            name='learn_type',
            field=models.IntegerField(choices=[(0, 'VISUAL'), (1, 'VERBAL'), (2, 'LOGICAL')], default=0),
        ),
    ]
