# Generated by Django 2.2.1 on 2019-05-05 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20190505_0536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sublessonuserdata',
            name='time',
        ),
    ]
