# Generated by Django 2.2.1 on 2019-05-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_remove_sublessonuserdata_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='sublesson',
            name='markdown_expression',
            field=models.TextField(blank=True, null=True),
        ),
    ]
