# Generated by Django 2.2.1 on 2019-05-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_sublesson_markdown_expression'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sublessonuserdata',
            name='solved',
            field=models.IntegerField(default=0),
        ),
    ]
