# Generated by Django 2.2.1 on 2019-05-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20190505_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='sublessonuserdata',
            name='current_tries',
            field=models.IntegerField(default=1),
        ),
    ]
